# Generated by Django 2.0.7 on 2020-02-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200205_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_field',
            field=models.BooleanField(default=False),
        ),
    ]
